# Generated by Django 2.2.3 on 2019-07-27 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Portfolio',
            new_name='Section',
        ),
    ]
